import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';
import Papa from 'papaparse'

export default function Home() {
  const [csv, setCsv] = useState(null)

  const uploadToClient = (event) => {
    if (event.target.files && event.target.files[0]) {
      Papa.parse(event.target.files[0], {
        header: true,
        skipEmptyLines: true,
        encoding: "latin1",
        complete: (results) => {
          setCsv(results)
        }
      });
    }
  }

  const url = "https://2if3ql3yh8.execute-api.us-east-1.amazonaws.com/poll"

  const uploadToServer = async () => {
    const response = await fetch(url, {
      method: "POST",
      body: JSON.stringify(csv)
    })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <div>
            <h4>Select csv</h4>
            <input type="file" name="csv" onChange={uploadToClient} />
            <button
              className="btn btn-primary"
              type="submit"
              onClick={uploadToServer}
            >
              Send to server
            </button>
          </div>
        </div>
      </main>
    </>
  )
}
