service: api
app: principia-challenge
org: fbltr

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.9
  environment:
    S3_BUCKET_NAME: ${self:app}-${self:service}-bucket-${sls:stage}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource: '*'

functions:
  hello:
    handler: handler.hello
    layers:
      - arn:aws:lambda:${env:LAYER_NAME}:layer:base-python:1
    events:
      - httpApi:
          path: /
          method: post
  uploadPoll:
    handler: uploadPoll.uploadPoll
    layers:
      - arn:aws:lambda:${env:LAYER_NAME}:layer:base-python:1
    events:
      - httpApi:
          path: /poll
          method: post

resources:
  Resources:
    Uploads:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:app}-${self:service}-bucket-${sls:stage}
