service: api
app: principia-challenge
org: fbltr

frameworkVersion: '3'

useDotenv: true

custom:
  bucketName: ${self:service}-bucket-${sls:stage}

provider:
  name: aws
  runtime: python3.9
  environment:
    S3_BUCKET_NAME: ${self:custom:bucketName}

functions:
  hello:
    handler: handler.hello
    layers:
      - arn:aws:lambda:${env:LAYER_NAME}:layer:base-python:1
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    Uploads:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom:bucketName}
