service: api
app: principia-challenge
org: fbltr

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.9
  environment:
    POLL_BUCKET: ${self:app}-${self:service}-poll-bucket-${sls:stage}
    POPULATION_BUCKET: ${self:app}-${self:service}-population-bucket-${sls:stage}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource: '*'

functions:
  hello:
    handler: handler.hello
    layers:
      - arn:aws:lambda:${env:LAYER_NAME}:layer:base-python:3
    events:
      - httpApi:
          path: /
          method: post
  uploadPoll:
    handler: uploadPoll.uploadPoll
    layers:
      - arn:aws:lambda:${env:LAYER_NAME}:layer:base-python:3
    events:
      - httpApi:
          path: /poll
          method: post
  updateCityId:
    handler: updateCityId.updateCityId
    layers:
      - arn:aws:lambda:${env:LAYER_NAME}:layer:base-python:3
    events:
      - httpApi:
          path: /update-city-id
          method: get

resources:
  Resources:
    Poll:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:app}-${self:service}-poll-bucket-${sls:stage}
    Population:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:app}-${self:service}-population-bucket-${sls:stage}
